# P 581 Programming 01번 문제

In [26]:
class Point :
    def __init__ (self, x, y):
        self.x = x
        self.y = y
        
    def __str__(self):
        return "(%.2d, %.2d)" %(self.x, self.y) #여기까진 문제에서 주어진대로 식을 쓴것뿐이다.
    
class Point3D(Point):
    def __init__(self, x, y, z):              
        super().__init__(x, y)                  #부모 클래스의 생성자를 명시적으로 호출
        self.z = z
        
    def __str__(self):
        return "(%.2d, %.2d, %.2d)" %(self.x, self.y, self.z)  #z변수가 추가된 만큼 이 메소드도 오버라이딩해줘야한다
    
a = Point(1, 2)
print(a)

b = Point3D(1, 2, 3)
print(b)

(01, 02)
(01, 02, 03)


# P 582  Programming 05번 문제

In [45]:
class Animal :
    def __init__(self, age):
        self.age = age
        
    def eat(self):
        print("동물이 먹고 있습니다.")      #여기까지는 본문내용이다
        
class Cat(Animal):                         
    def __init__(self, age, name, breed):  #문제에서 주어진 속성들을 인스턴스 변수로 정의
        super().__init__(age)              #부모클래스 생성자 호출
        self.name = name
        self.breed = breed
    
a=Cat(10, "meow", "no")
b=Cat(5, "takealook", "no")
c=Cat(1, "nya", "no")
    
def get_oldest_cat(*args):               #최대값을 반환하는 함수를 만든다
    return max(args)
    
d = get_oldest_cat(a.age, b.age, c.age)  #위에서 만든 함수를 알아서 고양이들의 '나이'를 최대값으로 반환해주지 않으므로 a,b,c대신 각각 a.age, b.age, c.age를 넣고 함수를 작동시킨다
print(f"가장 나이가 많은 고양이는 {d}살입니다.")
        

가장 나이가 많은 고양이는 10살입니다.


## Animal 관련 코드가 본문에 두개있길래 혹시나 해서

In [ ]:
class Animal(object):
    pass

class Dog(Animal):
    def __init__(self, name):
        self.name = name

class person(object):
    def __init__(self, name):
        self.name = name
        self.pet = None

# P 640  Programming 06번 문제

In [3]:
import numpy as np        #numpy 모듈을 불러온다

a = np.random.randn(3,3)   #3X3 난수로 행렬을 만든다
print(a)                   #행렬이 잘 생성되었는지 확인

a = (a - 0) / 1     #위와 같이 난수로 행렬을 만들면 평균값은 0 표준편차는 1이 되므로 이와 같이 정규화가 진행된다. 즉, 값이 변하지 않는다.
print(a)            #정규화된 행렬을 확인

[[ 0.90822229 -0.82534415  0.0959857 ]
 [-3.0092013  -0.07364819  0.20033007]
 [ 0.66202902  0.24112698 -0.31134867]]
[[ 0.90822229 -0.82534415  0.0959857 ]
 [-3.0092013  -0.07364819  0.20033007]
 [ 0.66202902  0.24112698 -0.31134867]]


In [9]:
import numpy as np

m, sigma = 10, 2                   #평균값(m)과 표준편차(sigma)를 다르게 하기 위해 이와 같이 변수를 설정한다
a = m+sigma*np.random.randn(3,3)  #평균값 10, 표준편차 2인 3X3 행렬을 난수로 만든다
print(a)                           #만들어진 행렬 확인

a = (a - m) / sigma               #정규화 진행
print(a)                          #정규화된 행렬 확인

[[ 8.66129575 13.48932789 14.72860531]
 [ 9.03748992 11.22455484 10.34545335]
 [10.61741269 11.17681658 11.22876516]]
[[-0.66935212  1.74466394  2.36430265]
 [-0.48125504  0.61227742  0.17272667]
 [ 0.30870635  0.58840829  0.61438258]]


## 최종본(준한이거 참고)

In [38]:
import numpy as np        #numpy 모듈을 불러온다

a = np.random.randn(3,3)   #3X3 난수로 행렬을 만든다
print(a)                   #행렬이 잘 생성되었는지 확인
mean = a.mean()            # 행렬의 평균값을 변수에 저장
std = a.std()              # 행렬의 표준편차를 변수에 저장
print((a-mean)/std)        # 정규화후 다시 출력


[[ 0.1656191   1.80158248 -1.61265475]
 [ 0.40667336 -0.18493221 -0.2243075 ]
 [-1.15363273  1.101509    0.72480902]]
[[ 0.05154855  1.68059771 -1.71920961]
 [ 0.29158403 -0.29752118 -0.33673006]
 [-1.26212759  0.98348302  0.60837512]]


# P 640  Programming 08번 문제

In [20]:
import numpy as np

b = np.arange(0,9).reshape(3,3)       #hint에서 말해준 부분

print("원본 배열:\n", b)              #원본 배열 출력
print("모든 요소의 합:", b.sum())     #sum 내장 함수로 모든 요소의 합계 구함
print("각 열의 합:", b.sum(axis=0))   #axix 내장 함수로 axis=0인 직선(행렬의 열)을 따라 통계값을 계산한다
print("각 행의 합:", b.sum(axis=1))   #axix 내장 함수로 axis=1인 직선(행렬의 행)을 따라 통계값을 계산한다


원본 배열:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
모든 요소의 합: 36
각 열의 합: [ 9 12 15]
각 행의 합: [ 3 12 21]


# Exercise 07번

In [28]:
class X :
    def __init__(self, a):
        self.a = a
    def inc(self):
        self.a+=1
        
class Y(X) :
    def __init__(self, b):
        super().__init__(10)
        self.b = b
    def inc(self):
        self.a+=10
        
o = Y(10)
o.inc()
print(o.a)

20
