# 파이썬 실습

## 1-1.이산수학이란?

### [실습] 동전교환 프로그램

In [4]:
# 변수 선언
c500, c100, c50, c10 = 0, 0, 0, 0 

# 동전 교환할 금액 입력받기
money = int(input("동전으로 교환할 금액을 입력하세요: "))
print('-'*40)

# 각 동전 갯수 계산
c500 = money // 500     # 500으로 나눈 몫
money= money % 500      # 500으로 나눈 나머지

c100 = money // 100     # 100으로 나눈 몫
money= money % 100      # 100으로 나눈 나머지

c50 = money // 50       # 50으로 나눈 몫
money= money % 50       # 50으로 나눈 나머지

c10 = money // 10       # 10으로 나눈 몫
money= money % 10       # 10으로 나눈 나머지

print("500원짜리 ==> %d개" % c500)
print("100원짜리 ==> %d개" % c100)
print("50원짜리 ==> %d개" % c50)
print("10원짜리 ==> %d개" % c10)
print("잔돈  ==> %d원" % money)

동전으로 교환할 금액을 입력하세요: 4321
----------------------------------------
500원짜리 ==> 8개
100원짜리 ==> 3개
50원짜리 ==> 0개
10원짜리 ==> 2개
잔돈  ==> 1원


-------------------

## 1-2.마술카드


### [실습] : 1~7 까지의 임의의 숫자를 생각하고 알아 맞추기

In [7]:
def my_card(index):
    cardname = chr(ord('A') + index - 1)

    while True:
        print(f" --------- {cardname} 카드 ---------\n")
        for i in range(0, 2):
            for j in range(0, 2):
                print("%7d" % card[index-1][i*2 + j], end='')
            print()
        
        print(" --------------------------\n")
        script = f"{cardname} 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.: "
        result = int(input(script))
        print("")

        if result in [0,1]:
            return result


def my_res(a,b,c):
    #res = (c*2*2) + (b*2) + (a)
    res = (c*2**2) + (b*2) + (a)
    print('-'*50)
    print("당신이 마음에 드는 숫자는 [[ %d ]]입니다.\n" % res);
    print("어때요? 신기하죠!!");
    print("지금까지 마술의 세계였습니다."); 
    print('-'*50, '끝')

#---------메인------------  
card = [
    [1,3,5,7],
    [2,3,6,7],
    [4,5,6,7]
    ]

print("# 지금부터 여러분을 신비한 마술의 세계로 초대합니다.")
print("1 - 7의 숫자중 마음에 드는 숫자를 생각해 보세요.")

n = input("생각하셨어요? 시작하려면 엔터를 누르세요.")
print('-'*50)
print()

a = my_card(1)
b = my_card(2)
c = my_card(3)

my_res(a,b,c)



# 지금부터 여러분을 신비한 마술의 세계로 초대합니다.
1 - 7의 숫자중 마음에 드는 숫자를 생각해 보세요.
생각하셨어요? 시작하려면 엔터를 누르세요.
--------------------------------------------------

 --------- A 카드 ---------

      1      3
      5      7
 --------------------------

A 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.0

 --------- B 카드 ---------

      2      3
      6      7
 --------------------------

B 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.1

 --------- C 카드 ---------

      4      5
      6      7
 --------------------------

C 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.1

--------------------------------------------------
당신이 마음에 드는 숫자는 [[ 6 ]]입니다.

어때요? 신기하죠!!
지금까지 마술의 세계였습니다.
-------------------------------------------------- 끝


### [실습] 1~31까지의 임의의 숫자를 생각하고 알아 맞추기

In [5]:
def my_card(index):
    cardname = chr(ord('A') + index - 1)

    while True:
        print(" --------- %s 카드 ---------\n" % cardname )
        for i in range(0, 4):
            for j in range(0, 4):
                print("%7d" % card[index-1][i*4 + j], end='')
            print()
        
        print(" --------------------------\n")
        script = "%s 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요."
        result = int(input(script % cardname))
        print("")

        if result in [0,1]:
            return result


def my_res(a,b,c,d,e):
    #res = (e*2*2*2*2) + (d*2*2*2) + (c*2*2) + (b*2) + (a)
    res = (e*2**4) + (d*2**3) + (c*2**2) + (b*2) + (a)
    print('-'*50)
    print("당신이 마음에 드는 숫자는 [[ %d ]]입니다.\n" % res);
    print("어때요? 신기하죠!!");
    print("지금까지 마술의 세계였습니다."); 
    print('-'*50, '끝')

#---------메인------------  
card = [
    [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31],
    [2,3,6,7,10,11,14,15,18,19,22,23,26,27,30,31],
    [4,5,6,7,12,13,14,15,20,21,22,23,28,29,30,31],
    [8,9,10,11,12,13,14,15,24,25,26,27,28,29,30,31],
    [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
    ]

print("# 지금부터 여러분을 신비한 마술의 세계로 초대합니다.")
print("1 - 31의 숫자중 마음에 드는 숫자를 생각해 보세요.")

n = input("생각하셨어요? 시작하려면 엔터를 누르세요.")
print('-'*50)
print()

a = my_card(1)
b = my_card(2)
c = my_card(3)
d = my_card(4)
e = my_card(5)

my_res(a,b,c,d,e)



# 지금부터 여러분을 신비한 마술의 세계로 초대합니다.
1 - 31의 숫자중 마음에 드는 숫자를 생각해 보세요.
생각하셨어요? 시작하려면 엔터를 누르세요.
--------------------------------------------------

 --------- A 카드 ---------

      1      3      5      7
      9     11     13     15
     17     19     21     23
     25     27     29     31
 --------------------------

A 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.2

 --------- A 카드 ---------

      1      3      5      7
      9     11     13     15
     17     19     21     23
     25     27     29     31
 --------------------------

A 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.0

 --------- B 카드 ---------

      2      3      6      7
     10     11     14     15
     18     19     22     23
     26     27     30     31
 --------------------------

B 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(0)을 입력해 주세요.1

 --------- C 카드 ---------

      4      5      6      7
     12     13     14     15
     20     21     22     23
     28     29     30     31
 --------------------------

C 카드에 생각한 숫자가 있다면 YES(1),없다면 NO(

---------------------------

In [2]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 

-------------------

## 1-3.자연수와 정수의 성질

### [실습] 어떤 수가 정수인지 판단하는 프로그램

In [1]:
# 정수 판별 프로그램
def is_integer(N):
    if N - int(N) == 0:
        print("정수")
    if N - int(N) != 0:
        print("소수")

try:
    N = input('숫자를 입력하세요: ')
    N = float(N)
    is_integer(N)
except ValueError:
    print("math error")

숫자를 입력하세요: -10
정수


### [실습] : 어떤 수가 소수인가 판단하는 프로그램

In [1]:
# 소수 판별하기
def is_prime_number(x):
    for i in range(2, x):
        if x % i == 0 and x != i:
            return False # 소수가 아님
    return True          # 소수임

# 자연수 N을 입력한다.
x = int(input('\n소수 판별하기 위한 정수 값을 입력해 주세요 : '))
print('-'*50)
if is_prime_number(x):
    print(f'{x} --> Prime number!!')
else:
    print(f'{x} --> Not Prime number!!')



소수 판별하기 위한 N 값을 입력해 주세요 : 123
--------------------------------------------------
  123 --> Not Prime number!!



### [실습] : 개선된 소수판별 프로그램 
- 제곱근 표시 : math.sqrt(x),   x**(1/2)

In [3]:
import math

def is_prime_number(x):
    for i in range(2, int(math.sqrt(x)) + 1):
#     for i in range(2, x**(1/2) + 1)
        if x % i == 0 and x != i:
            return False 
    return True 

# 자연수 N을 입력한다.
x = int(input('\n소수 판별하기 위한 정수 값을 입력해 주세요 : '))
print('-'*50)
if is_prime_number(x):
    print(f'{x} --> Prime number!!')
else:
    print(f'{x} --> Not Prime number!!')


소수 판별하기 위한 N 값을 입력해 주세요 : 49
--------------------------------------------------
49 --> Not Prime number!!


- **소수판별 시간 체크하기**(여러번 실행한 후에 시간을 비교해본다.)

In [5]:
import math
import timeit

def is_prime_number1(x):
    for i in range(2, x):
        if x % i == 0 and x != i:
            return False # 소수가 아님
    return True          # 소수임

def is_prime_number2(x):
    for i in range(2, int(math.sqrt(x)) + 1):
        if x % i == 0 and x != i:
            return False 
    return True 

x = 1597
start = timeit.default_timer()
is_prime_number1(x)
end = timeit.default_timer()
print(end - start)

start = timeit.default_timer()
is_prime_number2(x)
end = timeit.default_timer()
print(end - start)


0.000247500000114087
0.00020260000019334257


### [실습] 암스트롱 수 구하기
- Armstrong Number(암스트롱 수)란 세자리의 자연수로 각 자리수의 세제곱의 합이 자기 자신의 수와  같은 수

In [14]:
def is_amstrong_number(x):
    
    if x == int(str(x)[0])**3 + int(str(x)[1])**3 + int(str(x)[2])**3:
        return True
    else:
        return False
    

print('세 자리의 자연수인 암스트롱 수는: ')
for x in range(100, 1000, 1):
    if is_amstrong_number(x):
        print(x, end=' ')
    

세 자리의 자연수인 암스트롱 수는: 
153 370 371 407 

-------------------------------

## 1-4.행렬

### Numpy
고 성능 수치연산과 행렬식을 위한 라이브러리 설치하기

In [75]:
!pip install numpy


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### Numpy 라이브러리 특징

- ndarray : n차원 배열 데이터 구조
- np.array(): ndarray 생성 (ex: arr = np.array([[5,2],[10,3]])  )

### 행렬을 이용하여 연립방정식 풀기
5개의 빵과 2개의 우유를 사면 3000원을 지불해야하며, 10개의 빵과 3개의 우유를 사면 5000원을 지불해야 할때, 빵(x)과 우유(y) 각 1개씩의 가격은 얼마인가?


In [25]:
import numpy as np

arr1 = np.array([[5,2],[10,3]])
arr2 = np.array([3000,5000])

result = np.linalg.solve(arr1, arr2) #행렬
print(result)         # 연립방정식 결과
print(result.dtype)   # 결과 data type

[ 200. 1000.]
float64


### [예제-실생활에서 행렬이 사용된 예제] 이미지 처리

In [ ]:
!pip install opencv-python

In [ ]:
import cv2
cv2.__version__

In [6]:
import sys
import numpy as np
import cv2

src = cv2.imread('image/lenna.bmp', cv2.IMREAD_GRAYSCALE)

if src is None:
    print('Image load failed!')
    sys.exit()

# 부드럽게
mask = np.array([[1/9,1/9,1/9],
                [1/9,1/9,1/9],
                [1/9,1/9,1/9]])
mask = np.ones((3,3), dtype=np.float64)/ 9.

dst1 = cv2.filter2D(src, -1, mask) # 부드럽게


# 날카롭게
mask = np.array([[0,-1,0],
                [-1,4,-1],
                [0,-1,0]])

dst2 = cv2.filter2D(src, -1, mask) # 날카롭게

cv2.imshow('src', src)
cv2.imshow('blur', dst1)
cv2.imshow('sharp', dst2)

cv2.waitKey()             # 키가 눌려질때까지 기다리기
cv2.destroyAllWindows()

#### 실시간 영상 이미지에 필터값 적용

In [7]:
import sys
import cv2

def cartoon_filter(img):
    h, w = img.shape[:2]
    img2 = cv2.resize(img, (w//2, h//2))

    blr = cv2.bilateralFilter(img2, -1, 20, 7)
    edge = 255 - cv2.Canny(img2, 80, 120)
    edge = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)

    dst = cv2.bitwise_and(blr, edge)
    dst = cv2.resize(dst, (w, h), interpolation=cv2.INTER_NEAREST)
    return dst


def pencil_sketch_filter(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blr = cv2.GaussianBlur(gray, (0, 0), 3)
    dst = cv2.divide(gray, blr, scale=255)
    return dst

# 실시간 카메라 작동
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print('Video open failed!')
    sys.exit()

cam_mode = 0    
while True:
    ret, frame = cap.read()
    if not ret:
        print('Video read failed!')
        break
            
    # 모드에 따라 필터 적용한 영상(frame) 보여주기
    if cam_mode == 1:
        frame = cartoon_filter(frame)
        title = f'{cam_mode} : cartoon_filter'
        tcolor = (255,0,255)
    elif cam_mode == 2:
        frame = pencil_sketch_filter(frame)
        title = f'{cam_mode} : pencil_sketch_filter'
        tcolor = (0,0,0)
    else:
        title = f'{cam_mode} :  '
        tcolor = (0,0,0)
    
    cv2.putText(frame, title, (30, 30),
            cv2.FONT_HERSHEY_DUPLEX, 1, 
             tcolor, 2, cv2.LINE_AA)
    cv2.imshow('frame', frame)
    

    key = cv2.waitKey(1)
    if key==27: # ESC키 눌러졌을 때
        break
    elif key==ord(' '): #스페이스키 눌러졌을 때
        cam_mode += 1        
        print(f'cam_mode:{cam_mode}')
        if cam_mode==3:
            cam_mode = 0
    
cap.release()
cv2.destroyAllWindows()
print('Video Finish!')

cam_mode:1
cam_mode:2
cam_mode:3
cam_mode:1
cam_mode:2
cam_mode:3
cam_mode:1
Video Finish!


----------------------------

### [예제 1-9] 행렬의 합

In [20]:
import numpy as np

arr1 = np.array([[3,4,-1],[5,0,-2]])
arr2 = np.array([[4,5,3],[0,-3,2]])

print(arr1 + arr2)

[[ 7  9  2]
 [ 5 -3  0]]


### [예제 1-10] 스칼라 곱

In [26]:
import numpy as np

A = np.array([[2,-3,4],[6,9,0]])
c = 2

print(c * A)

[[ 4 -6  8]
 [12 18  0]]


### [예제 1-11] 행렬의 곱
- np.dot(A, B) 
- 행렬의 곱은 사칙연산의 * 와 다른 @ 기호를 사용한다.

In [57]:
import numpy as np

A = np.array([[2,1],[3,-2]])
B = np.array([[1,-1],[2,-3]])

print( np.dot(A, B) )
print( np.dot(B, A) )

[[ 4 -5]
 [-1  3]]
[[-1  3]
 [-5  8]]


In [28]:
import numpy as np

A = np.array([[2,1],[3,-2]])
B = np.array([[1,-1],[2,-3]])

print(A @ B)
print(B @ A)

[[ 4 -5]
 [-1  3]]
[[-1  3]
 [-5  8]]


### 특수 행렬
- numpy 행렬을 위한 참고 정보

|구분 |영문설명| numpy.함수명()|
|:---|:---|:---|
|대각행렬|Diagonal matrix | np.diag(x) |
|내적(행렬 곱)|Dot Product, Inner product| np.dot(a,b) , a @ b|
|대각합|Trace | np.trace(x)|
|행렬식|Matrix Deteminant  | np.linalg.det(x) |
|역행렬|Inverse of a matrix  | np.linalg.inv(x) |
|고유값, 고유벡터 |Eigenvalue, Eigenvector  | w, v = np.linalg.eig(x) |
|특이값 분해 |Singular value Decomposition  |u,s,vh = np.linalg.svd(A) |
|연립방정식 해 풀기 |Solve a linear matrix equation  | np.linalg.slove(a, b) |
|최소자승 해 풀기 |Compute the Least-squares solution  | m, c = np.linalg.lstsq(A,y,rcond=None)[0] |

#### 대각행렬
- 정방 행렬에서 주대각 원소를 제외한 나머지 원소(off-diagonal)가 모두 0인 행렬
- np.diag(x) 대각행렬의 원소 추출하는 함수

In [45]:
matrix = np.array([[2,0,0],[0,3,0],[0,0,4]])

print( '행렬: \n',  matrix ) 
print( '대각행렬: ', np.diag(matrix) )     # 대각행렬 추출하기

행렬: 
 [[2 0 0]
 [0 3 0]
 [0 0 4]]
대각행렬:  [2 3 4]


In [38]:
matrix = np.arange(9).reshape(3,3)

print( '행렬: \n',  matrix )               # 행렬
print( '대각행렬: ', np.diag(matrix) )     # 대각행렬 추출하기
print( '대각행렬: ', np.diag(matrix, k=1) )# k - start index

행렬: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
대각행렬:  [0 4 8]
대각행렬:  [1 5]


#### 단위 행렬
- 주대각 원소들은 모두 1을 갖고 나머지 원소들은 모두 0인 행렬

In [54]:
np.identity(3, dtype=np.int8)  # 행이 3개인 단위 행렬

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [53]:
np.eye(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [51]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

#### 전치 행렬
- A가 임의의 𝐧×m 행렬일 때 A의 전치 행렬은 $𝐀^𝐓$로 표기하고 A의 행과 열을 바꾸어서 얻어진 m×n 행렬
- A.transpose()

In [91]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2,3],[4,5,6]])

print(A)  ; print('-'*10)
print(A.T); print('-'*10)
print(B)  ; print('-'*10)
print(B.T); print('-'*10)
print(B.transpose()); print('-'*10)

[[1 2]
 [3 4]]
----------
[[1 3]
 [2 4]]
----------
[[1 2 3]
 [4 5 6]]
----------
[[1 4]
 [2 5]
 [3 6]]
----------
[[1 4]
 [2 5]
 [3 6]]
----------


#### 상삼각 행렬

In [55]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

#### 하삼각 행렬

In [56]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

#### 역행렬 : [ 예제 1-16] 

In [74]:
import numpy as np

A = np.array([[2,-5],[-1,3]])
B = np.linalg.inv(A)

print(A); print('-'*10)
print(B); print('-'*10)

[[ 2 -5]
 [-1  3]]
----------
[[3. 5.]
 [1. 2.]]
----------


### [ 예제 1-18] 역행렬  

In [83]:
import numpy as np

A = np.array([[3,5],[2,3]])
B = np.linalg.inv(A)

print(A); print('-'*10)
print(B); print('-'*10)

[[3 5]
 [2 3]]
----------
[[-3.  5.]
 [ 2. -3.]]
----------


#### numpy 역행렬 확인하기

In [88]:
from numpy.linalg import inv

A = np.array([[3,5],[2,3]])
Ainv = inv(A)

print( np.allclose(np.dot(A, Ainv), np.eye(2)) )
print( np.allclose(np.dot(Ainv, A), np.eye(2)) )

True
True


### [ 예제 1-19] 직교행렬 여부 판단하기
- 직교행렬 : $A^-1$ = $A^T$가 되는 행렬

In [90]:
from numpy.linalg import inv

A = np.array([[3,5],[2,3]])
Ainv = inv(a)
AT = A.T

print( np.allclose(Ainv, AT) )

False


In [125]:
import numpy as np

A = np.array([[1,0,1],[0,1,1],[1,1,0],[0,0,0]])
B = np.array([[1,1,0],[1,0,1],[0,0,1],[1,1,0]])
C = np.array([[1,0,0],[0,1,1],[1,0,1]])

print(A | B) ; print('-'*10)  # 요소간의 합집합
print(A & B) ; print('-'*10)  # 요소간의 교집합

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 0]]
----------
[[1 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]
----------


### [예제 1-21] 행렬식 구하기

In [97]:
import numpy as np

A = np.array([[3,2],[4,6]])
result = np.linalg.det(A)

print(A)
print(np.int8(result))

[[3 2]
 [4 6]]
10


### [예제 1-22] 행렬식 구하기

In [98]:
import numpy as np

A = np.array([[5,4,0],[6,7,2],[0,9,3]])
result = np.linalg.det(A)

print(A)
print(np.int8(result))

[[5 4 0]
 [6 7 2]
 [0 9 3]]
-57


#### 고유값과 고유벡터
- 행렬 A를 선형변환으로 봤을 때, 선형변환 A에 의한 변환 결과가 자기 자신의 상수배가 되는 0이 아닌 벡터를고유벡터(eigenvector)라 하고 
- 이 상수배 값을 고유값(eigenvalue)이라 한다

### [예제 1-26] 고유값과 고유벡터 구하기

In [128]:
import numpy as np

A = np.array([[2,1],[3,4]])

# 고유값(w), 고유벡터(v)
w, v = np.linalg.eig(A)

print(w, v)
# 선형 변환을 했을 때 그 크기는 변하고 
# 방향이 변하지 않는 벡터가 있다고 할 때, 
# 그 벡터의 크기는 각각 1배와 5배가 된다는 의미

[1. 5.] [[-0.70710678 -0.31622777]
 [ 0.70710678 -0.9486833 ]]
