In [5]:
def recursion(n):
    return recursion(n-1) + recursion(n-2) if n >= 3  else 1
n = 20
print(f'n={n}, recursion(20)={recursion(n)}')

n=20, recursion(20)=6765


In [17]:
original = ' ABCDEFGHIJKLMNOPQRSTUVWXYZ'
cypher = 'EIJFUAXVHWP CSRKOBTQYDMLZNG'
def encryption(words): # 암호화
    message = ''
    for c in words:
        idx = original.find(c)
        message += cypher[idx]
    return message

def decryption(words): #복호화
    message = ''
    for c in words:
        idx = cypher.find(c)
        message += original[idx]
    return message


word1 = 'have to study'
word2 = 'UWQFTAYAESIYHASIYWFQ'
print(f'암호화할 메시지:{word1} 암호화 결과:{encryption(word1).upper()}')    
print(f'복호화할 메시지:{word2} 복호화 결과:{decryption(word2).lower()}') 

암호화할 메시지:have to study 암호화 결과:GGGGEGGEGGGGG
복호화할 메시지:UWQFTAYAESIYHASIYWFQ 복호화 결과:discrete mathematics


In [25]:
import numpy as np

# 숫자 순서쌍으로 변환
def convertEdgeToNum(V, E):
    # 만약 V 원소가 String일 경우 숫자 순서쌍으로 변환하기
    if any(isinstance(v, str) for v in V):
        data  = { v:idx+1 for idx, v in enumerate(V) }  # V 원소 숫자로 표시
        result= [(data[v1], data[v2])  for v1, v2 in E] # E 순서쌍으로 표시    
        return result
    else:
        return E

def makeMatirx(V, E):
    
    # 만약 V 원소가 String일 경우 숫자 순서쌍으로 변환하기
    E = convertEdgeToNum(V, E)
    print(E)

    # 빈(0) 행렬 만들기
    adj = [[0 for _ in range(len(V))] for _ in range(len(V))]

    # 인접 행렬 만들기
    for t in E:
        src, dest = t
        adj[src-1][dest-1] = 1

    print(np.array(adj) )        
    return np.array(adj) 

V = {1,2,3,4,5,6}
E = {(1,2),(1,4),(1,6),(2,3),(3,4),(4,2),(5,4),(5,6),(6,4)} 

print('#유향 그래프 인접행렬:')
makeMatirx(V, E)  # 유향 그래프 인접행렬

# 연결리스트 만들기
def makeLinkedList(V, E):
    
    # 만약 V 원소가 String일 경우 숫자 순서쌍으로 변환하기
    E = convertEdgeToNum(V, E)
    
    adj = [[] for _ in range(len(V))]

    for t in E:
        src, dest = t    
        
        adj[src-1].append(dest)
    
    # 연결 리스트 출력하기
    if isinstance(V, str): # V 원소가 문자인 경우
        for idx, v in enumerate(adj):
            v.sort()
            print(f'v[{V[idx]}]의 연결 리스트 =  {V[v-1]}')
    else:
        for idx, v in enumerate(adj):
            v.sort()
            print(f'v[{idx+1}]의 연결 리스트 =  {v}')
        
    return adj

print()
print('#유향 그래프 연결리스트:')
makeLinkedList(V, E)  # 유향 그래프 인접행렬

#유향 그래프 인접행렬:
{(1, 2), (3, 4), (5, 4), (6, 4), (1, 4), (4, 2), (2, 3), (5, 6), (1, 6)}
[[0 1 0 1 0 1]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 1]
 [0 0 0 1 0 0]]

#유향 그래프 연결리스트:
v[1]의 연결 리스트 =  [2, 4, 6]
v[2]의 연결 리스트 =  [3]
v[3]의 연결 리스트 =  [4]
v[4]의 연결 리스트 =  [2]
v[5]의 연결 리스트 =  [4, 6]
v[6]의 연결 리스트 =  [4]


[[2, 4, 6], [3], [4], [2], [4, 6], [4]]