# 예제 4-42 와샬 알고리즘

In [11]:
import numpy as np

# 관계 행렬 만들기
def makeRelationMatrix(A, B, R):    
    import numpy as np
    
    datas = []
    for a in A: # 행
        data = []
        for b in B: # 열
            r = (a, b)
            if r in R: 
                data.append(1)
            else:
                data.append(0)
        datas.append(data)
        
    return np.array(datas)

A = [1, 2, 3, 4]

R = [(1,2),(2,1),(2,3),(3,4)]




### 와샬 알고리즘

n = len(A)

matrix0 = makeRelationMatrix(A, A, R)

for l in range(n) :
    print(f"W{l}=")
    print(globals()['matrix{}'.format(l)])
    print('-'*30)
    globals()['matrix{}'.format(l+1)] = globals()['matrix{}'.format(l)]
    
    a=0
    c=[]
    for i in globals()['matrix{}'.format(l)][:, l] :
        if i == 1 :
            c.append(a)
        a=a+1

    b=0
    d=[]
    for i in globals()['matrix{}'.format(l)][l,:] :
        if i == 1 :
            d.append(b)
        b=b+1

    for i in c :
        for j in d :
            globals()['matrix{}'.format(l+1)][i, j] = 1

print(f"W{l+1}=")
print(globals()['matrix{}'.format(l+1)])


W0=
[[0 1 0 0]
 [1 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
------------------------------
W1=
[[0 1 0 0]
 [1 1 1 0]
 [0 0 0 1]
 [0 0 0 0]]
------------------------------
W2=
[[1 1 1 0]
 [1 1 1 0]
 [0 0 0 1]
 [0 0 0 0]]
------------------------------
W3=
[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 1]
 [0 0 0 0]]
------------------------------
W4=
[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 1]
 [0 0 0 0]]


# 연습문제 52

In [3]:
import numpy as np

# 관계 행렬 만들기
def makeRelationMatrix(A, B, R):    
    import numpy as np
    
    datas = []
    for a in A: # 행
        data = []
        for b in B: # 열
            r = (a, b)
            if r in R: 
                data.append(1)
            else:
                data.append(0)
        datas.append(data)
        
    return np.array(datas)

A = [1, 2, 3]

R = [(1,1),(1,2),(2,3),(1,3),(3,1),(3,2)]




### 와샬 알고리즘

n = len(A)

matrix0 = makeRelationMatrix(A, A, R)

for l in range(n) :
    print(f"W{l}=")
    print(globals()['matrix{}'.format(l)])
    print('-'*30)
    globals()['matrix{}'.format(l+1)] = globals()['matrix{}'.format(l)]
    
    a=0
    c=[]
    for i in globals()['matrix{}'.format(l)][:, l] :
        if i == 1 :
            c.append(a)
        a=a+1

    b=0
    d=[]
    for i in globals()['matrix{}'.format(l)][l,:] :
        if i == 1 :
            d.append(b)
        b=b+1

    for i in c :
        for j in d :
            globals()['matrix{}'.format(l+1)][i, j] = 1

print(f"W{l+1}=")
print(globals()['matrix{}'.format(l+1)])

W0=
[[1 1 1]
 [0 0 1]
 [1 1 0]]
------------------------------
W1=
[[1 1 1]
 [0 0 1]
 [1 1 1]]
------------------------------
W2=
[[1 1 1]
 [0 0 1]
 [1 1 1]]
------------------------------
W3=
[[1 1 1]
 [1 1 1]
 [1 1 1]]
